apiVersion: v1
kind: Namespace
metadata:
  name: multi-threaded-permutations

---


apiVersion: batch/v1
kind: Job
metadata:
  namespace: multi-threaded-permutations
  name: multi-threaded-permutations-generator
spec:
  template:
    spec:
      containers:
        - name: multi-threaded-permutations
          image: maartendev/multi-threaded-permutations
      restartPolicy: Never
  backoffLimit: 4

---

## Database
kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: multi-threaded-permutations
  name: multi-threaded-permutations-db-pv
  labels:
    app: multi-threaded-permutations
    tier: persistence
spec:
  storageClassName: standard
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/databasedata/multi-threaded-permutations-db"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: multi-threaded-permutations-db-pv-claim
  namespace: multi-threaded-permutations
  labels:
    app: multi-threaded-permutations
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  selector:
    matchLabels:
      app: multi-threaded-permutations
      tier: persistence
---

apiVersion: v1
kind: Service
metadata:
  name: multi-threaded-permutations-db
  namespace: multi-threaded-permutations
  labels:
    app: multi-threaded-permutations
spec:
  ports:
    - port: 1433
  selector:
    app: multi-threaded-permutations
    tier: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-threaded-permutations-db
  namespace: multi-threaded-permutations
  labels:
    app: multi-threaded-permutations
spec:
  selector:
    matchLabels:
      app: multi-threaded-permutations
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: multi-threaded-permutations
        tier: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2017-latest
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              value: "Developer"
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              value: "yourStrong(!)Password"
          volumeMounts:
            - name: persistent-storage
              mountPath: /var/opt/mssql
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: multi-threaded-permutations-db-pv-claim